name: update team users
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
    paths: ["**/users"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create teams from directories
        uses: jcantosz/update-teams/create-teams-from-directories@v0.0.1
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.private_key }}
          installation_id: ${{ secrets.installation_id }}
          organization_name: "jcantosz-test-org"

      - name: Sync team repositories
        uses: jcantosz/update-teams/sync-users@v0.0.1
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.private_key }}
          client_id: ${{ secrets.client_id }}
          client_secret: ${{ secrets.client_secret }}
          installation_id: ${{ secrets.installation_id }}
          organization_name: "jcantosz-test-org"
